# Generated by Django 3.2.8 on 2022-02-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_p',
            field=models.IntegerField(null=True, verbose_name='Discount percent'),
        ),
    ]
