# Generated by Django 3.2.8 on 2022-02-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_p',
            new_name='discount_percent',
        ),
    ]
